# Generated by Django 4.1.1 on 2022-09-20 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='room',
            name='creator_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
