# Generated by Django 4.1.1 on 2022-09-20 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_remove_room_creator_id_room_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='room',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='room',
            name='creator_id',
            field=models.IntegerField(default=0),
        ),
    ]
