# Generated by Django 4.1.1 on 2022-09-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_remove_room_creator_id_room_user_alter_room_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='code',
        ),
    ]
