# Generated by Django 4.1.1 on 2022-09-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_room_creator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator_id',
        ),
    ]
