# Generated by Django 4.1.1 on 2022-09-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_room_creator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='members',
        ),
    ]
