# Generated by Django 4.1.1 on 2022-09-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_room_creator_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
