# Generated by Django 4.1.1 on 2022-09-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_room_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
