# Generated by Django 4.1.1 on 2022-09-21 00:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_room_room_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('passing_percentage', models.FloatField()),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_limit', models.IntegerField(default=0)),
                ('close_at', models.DateTimeField()),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('room', models.ManyToManyField(to='quiz.room')),
            ],
        ),
    ]
