# Generated by Django 4.1.1 on 2022-09-21 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='close_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='publish_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_limit',
        ),
    ]
