# Generated by Django 4.1.1 on 2022-09-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
    ]
