# Generated by Django 4.1.1 on 2022-09-21 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='room',
            new_name='rooms',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
